### ISSUE TITLE
Use an InputStream or a Reader for response serialization instead of a String

### ISSUE THREAD

**Issue by mfornos** [CYFLabs/spreedly-java-client#5]
IMHO, passing the stream returned by HttpURLConnection.getInputStream (or a Reader over it) is a nicer approach (and adds less overhead) than transforming the stream to a string and re-processing it. Although the benefit depends on the underlying XML parser implementation. In the current case, _Simple XML_ tries to use any StAX implementation found in the classpath. So, it seems worth doing.

---

__Changes Needed__

See the TODO in https://github.com/CYFLabs/spreedly-java-client/blob/e5ffc343f3a3e6c6e74f6aa68270535e08d2de25/spreedly-java-client/src/main/java/spreedly/client/java/http/UrlConnectionHttpHandler.java#L152

Redefine the interface and implementation of https://github.com/CYFLabs/spreedly-java-client/blob/e5ffc343f3a3e6c6e74f6aa68270535e08d2de25/spreedly-java-client/src/main/java/spreedly/client/java/xml/XmlParser.java

Modify https://github.com/CYFLabs/spreedly-java-client/blob/e5ffc343f3a3e6c6e74f6aa68270535e08d2de25/spreedly-java-client/src/main/java/spreedly/client/java/http/Response.java to hold the reference to the stream/reader instead of body.

**Comment by agseco** [comment]
WIP

**Comment by facundofarias** [comment]
:+1:
